apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: quay.io/cbrintnall/minigame
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - src/manifests/*.yaml
