
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: proxies.arc.com
spec:
  scope: Namespaced
  group: arc.com
  versions:
    - name: v1alpha1
      served: true 
      storage: true
  names:
    kind: Proxy
    plural: proxies
    singular: proxy
    shortNames:
     - prox
     - pr
